module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf8ff',
        'surface-dim': '#dcd7ea',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f1ff',
        'surface-container': '#f0ebfe',
        'surface-container-high': '#ebe5f8',
        'surface-container-highest': '#e5e0f3',
        'on-surface': '#1c1a27',
        'on-surface-variant': '#474554',
        'inverse-surface': '#312f3d',
        'inverse-on-surface': '#f3eeff',
        outline: '#787586',
        'outline-variant': '#c8c4d6',
        'surface-tint': '#5648d1',
        primary: '#5445cf',
        'on-primary': '#ffffff',
        'primary-container': '#6d60e9',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#c5c0ff',
        secondary: '#006876',
        'on-secondary': '#ffffff',
        'secondary-container': '#3ee5fe',
        'on-secondary-container': '#006370',
        tertiary: '#8b4c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#af6100',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e4dfff',
        'primary-fixed-dim': '#c5c0ff',
        'on-primary-fixed': '#140067',
        'on-primary-fixed-variant': '#3d2bb9',
        'secondary-fixed': '#9eefff',
        'secondary-fixed-dim': '#28d9f3',
        'on-secondary-fixed': '#001f24',
        'on-secondary-fixed-variant': '#004e59',
        'tertiary-fixed': '#ffdcc2',
        'tertiary-fixed-dim': '#ffb77a',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#6d3a00',
        background: '#fcf8ff',
        'on-background': '#1c1a27',
        'surface-variant': '#e5e0f3',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'metric-display': ['24px', { lineHeight: '30px', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '24px',
        gutter: '16px',
        'card-padding': '20px',
        'section-gap': '32px',
        'element-gap': '12px',
      },
      boxShadow: {
        soft: '0px 10px 30px rgba(115, 103, 240, 0.08)',
        'soft-lg': '0px 10px 30px rgba(115, 103, 240, 0.15)',
        glow: '0px 10px 30px rgba(84, 69, 207, 0.25)',
      },
    },
  },
  plugins: [],
};
